Use 'key in dict' instead of 'key in dict.keys()'
OpenShot/openshot-qt pull request #4017
Opened 2021-02-20 10:51 UTC by MartinThoma

2021-03-23 07:10 UTC, ferdnyc reviewed
:+1:  Drives me nuts.

I had some suggestions, if we're going to be fixing things anyway...

(Unfortunately, because they cross deleted lines in the diff, I couldn't leave them as _actual_ suggestions that could be applied directly from the review interface.)

2021-03-23 07:27 UTC, ferdnyc commented
And _here_ (which extended too far outside the diff to review-comment on at all)...
https://github.com/OpenShot/openshot-qt/blob/c79d13f67be31877754f593f53e70e49471ed191/src/windows/views/files_treeview.py#L186-L195

that can all be just:
```python3
f.data.update({"name": name or os.path.basename(f.data.get("path"))})
if "tags" in f.data or tags:
    f.data.update({"tags": tags})
```
No real point in those equality tests, when **any** inequality results in an assignment. The lookup to get the current value _may_ be slightly cheaper than the assignment, but it's also completely redundant whenever the equality test fails. Might as well skip the test and just always do the assignment. If we assign the same value it already held, what's the harm?

2021-03-23 22:00 UTC, MartinThoma commented on src/windows/file_properties.py
>              tags = self.file.data["tags"]
I love it :heart_eyes: I'm super swamped with other work at the moment, but [I want to make this part of my flake8 plugin](https://github.com/MartinThoma/flake8-simplify/issues/50)

2021-03-23 23:38 UTC, ferdnyc requested changes
LGTM! One minor typo to fix, and then I'm good to merge. Thanks!

2021-03-23 23:38 UTC, ferdnyc commented on src/windows/file_properties.py
> +        name = file.data.get("name", filename)
You dropped the 'self' there:
```suggestion
        name = self.file.data.get("name", filename)
```
(Or maybe I did, in my suggestion. Certainly possible.)

2021-03-23 23:45 UTC, ferdnyc commented on src/windows/file_properties.py
>              tags = self.file.data["tags"]
That would be huge, code like this is _rampant_ throughout basically all Python codebases.

2021-03-24 01:27 UTC, ferdnyc commented on src/windows/file_properties.py
> +        name = file.data.get("name", filename)
Actually, I'm just gonna apply that (now that I've remembered I can do that), and then get this merged. Thanks again, @MartinThoma !

2021-03-24 01:27 UTC, ferdnyc approved these changes

2021-03-24 01:46 UTC, merged