Improved Waveforms (highly optimized)
OpenShot/openshot-qt pull request #4819
Opened 2022-06-02 03:42 UTC by jonoomph

Fixed many issues related to waveform generation and reuse. Added an Angular directive to watch for **audio_data** changes. Simplified the waveform process also. When no waveforms are present, *.osp file size does not change. When huge waveforms are displayed on many clips, the size of *.osp project will grow quite a bit. In fact, we might want to consider moving audio_data into some separate cache files, vs baking the audio_data into our *.osp file. Or at a minimum, allow the user to clear all audio data from an *.osp project (to reduce the size).

2022-06-02 19:29 UTC, jonoomph commented
![](https://github.trello.services/images/mini-trello-icon.png) [Waveforms disappear when re-opening a project](https://trello.com/c/8XV6Wl28/76-waveforms-disappear-when-re-opening-a-project)

2022-06-03 08:22 UTC, JacksonRG requested changes
A couple changes. But they're changes you've asked me to make on earlier PRs.

So here's a patch file with the fixes I'm asking for. (Plus it updates the waveform if you edit volume in the properties window)

[waveforms.zip](https://github.com/OpenShot/openshot-qt/files/8830809/waveforms.zip)

2022-06-03 08:22 UTC, JacksonRG commented on src/classes/waveform.py
> +                # After 15 seconds. Abandon
I know you had a nitpick (which I addressed) about avoiding literal numbers in comments. But that must've gotten undone in some version changing.

2022-06-03 08:22 UTC, JacksonRG commented on src/classes/waveform.py
> +        if clip_audio_data and clip_audio_data == [-999]:
I know I came up with this, but I think it has to go.

If we ctrl-z after a `show waveform` I think this will set us back to `-999`. But this time there's no thread working on it. So we can't re-show the waveform.

Would love to say I'm just *that* good at reading code. But I found this with a quick test.

For now I think ctrl-z is a more likely use case than pressing `show waveform` twice in under a second. Also without this we have the chance of repeating work. But with it we have the chance of a clip which *can't* show waveform.

2022-06-15 23:18 UTC, jonoomph commented
@JacksonRG LGTM - But before we merge these changes, I still have a few ideas / thoughts.  Based on the primary concern of *.osp files become very large, due primarily to waveform data. 

**Solution 1:** We add a menu option: "Edit -> Clear Waveforms", which clears all file **audio_data** and clip **audio_data** in the project JSON. Since the *.osp file size is only affected when generating large amounts of waveform data, giving users an easy way to remove this data seems important.

**Solution 2:** We store the **audio_data** outside of the *.osp (for example, in a separate `audio_data.json` file). Although this sounds great on the surface, it means that the data would not be easy to "bind" using Angular though... and would change this PR a bunch.

2022-06-28 16:39 UTC, JacksonRG commented
@jonoomph At this point, this PR's goals have been accomplished. There's still a little weird behavior.

1. Dragging sliders in the properties window when `Show Waveform` is activated is a little weird. The values change, but the sliders don't show it.
2. `Show Waveform` changes get added to Action History (though I have some stashed changes that wrap every change to `audio_data` in an `ignore_history`.

I understand if you want to get these changes merged, get feedback, and address those issues in their own tickets.

2022-06-29 23:24 UTC, JacksonRG approved these changes

2022-06-29 23:31 UTC, merged