Take 2: Qt6 readiness: Use typed enums
OpenShot/openshot-qt pull request #4836
Opened 2022-06-23 23:34 UTC by jonoomph

Updating code base (especially Qt enums) to be compatible with Qt6. This is mostly work from @ferdnyc and PR https://github.com/OpenShot/openshot-qt/pull/4833. I've made a few additional changes (formatting, bug fixes), but due to the older base of this PR (I think), I had trouble merging these changes back into the original PR.

2022-06-23 23:37 UTC, jonoomph commented
![](https://github.trello.services/images/mini-trello-icon.png) [PR: Support for PyQt6 (initial steps)](https://trello.com/c/qhKzSLUJ/149-pr-support-for-pyqt6-initial-steps)

2022-06-24 08:01 UTC, ferdnyc commented
@jonoomph 

Honestly? This doesn't sit right with me at all.

Never mind the pointlessness of leaving review comments on my other PR, then closing it before I could even address them. That's actually beside the point.

If you wanted to make changes to my commit, there are two different ways — no, wait, _three_ different ways — you could do that without obliterating the attribution. (Proper git attribution, not a note in a commit message.)

1. You could've created this branch, edited my PR to target it, and merged the PR to this branch
2. You could've `git cherry-pick`ed the commit from the PR branch in my fork into this branch, after creating it.
3. You could've used `git format-patch -1` from a checkout of my PR branch, to export my commit to a patch file, then run `git am 0001-Py-Qt6-readiness-Use-typed-enums.patch` from this branch to re-import the commit.

Any of those would keep my ID attached to my changes.

2022-06-24 19:49 UTC, JacksonRG requested changes
One line looks like it's missing an enum class. Other than that, looks good.

2022-06-24 19:49 UTC, JacksonRG commented on src/windows/export.py
> +            p.setColor(QPalette.Highlight, Qt.GlobalColor.green)
I saw other `QPalette.Highlight` replaced with `QPalette.ColorRole.Highlight`

2022-06-24 20:58 UTC, jonoomph commented
> @jonoomph
> 
> Honestly? This doesn't sit right with me at all.
> 
> Never mind the pointlessness of leaving review comments on my other PR, then closing it before I could even address them. That's actually beside the point.
> 
> If you wanted to make changes to my commit, there are two different ways — no, wait, _three_ different ways — you could do that without obliterating the attribution. (Proper git attribution, not a note in a commit message.)
> 
> 1. You could've created this branch, edited my PR to target it, and merged the PR to this branch
> 2. You could've `git cherry-pick`ed the commit from the PR branch in my fork into this branch, after creating it.
> 3. You could've used `git format-patch -1` from a checkout of my PR branch, to export my commit to a patch file, then run `git am 0001-Py-Qt6-readiness-Use-typed-enums.patch` from this branch to re-import the commit.
> 
> Any of those would keep my ID attached to my changes.

@ferdnyc Please calm down, no need to get aggressive. Nobody is trying to steal your attribution. I am fine merging your previous PR, if you can pull my changes from this branch and fix all the issues with the original PR. I spent an hour trying to merge changes into your branch unsuccessfully (not to mention prioritized this work above my own), and thus, created this one as a last ditch effort to move this forward. So, you can criticize my lack of git skills, sure, but let's not be overly emotional and accusatory. 

Closing this one for now (waiting on changes to the original)

2022-06-24 20:58 UTC, closed without merging